import { useEffect, useMemo, useState, type FormEvent, type ReactNode } from 'react'
import './App.css'
import './responsive.css'
import './theme.css'
import { erase, load, save } from './storage'
import { expensesByCategory, id, money, tax, totals, type Account, type Contact, type Data, type Invoice, type Transaction, type TxType } from './finance'

type Page = 'Dashboard' | 'Transactions' | 'Invoices' | 'Payments' | 'Income' | 'Expenses' | 'Customers' | 'Suppliers' | 'Accounts' | 'Tax Center' | 'Analytics' | 'Reports' | 'Country Guide' | 'Currencies' | 'Backup & Restore' | 'Settings' | 'About BalancePoint'
type Dialog = 'transaction' | 'invoice' | 'contact' | 'account' | null
const nav: { page: Page; icon: string }[] = [
  { page: 'Dashboard', icon: '▦' }, { page: 'Transactions', icon: '↔' }, { page: 'Invoices', icon: '▤' }, { page: 'Payments', icon: '◉' }, { page: 'Income', icon: '↗' }, { page: 'Expenses', icon: '↙' }, { page: 'Customers', icon: '♙' }, { page: 'Suppliers', icon: '♧' }, { page: 'Accounts', icon: '▣' }, { page: 'Tax Center', icon: '%' }, { page: 'Analytics', icon: '⌁' }, { page: 'Reports', icon: '▥' }, { page: 'Country Guide', icon: '◎' }, { page: 'Currencies', icon: '¤' }, { page: 'Backup & Restore', icon: '⤓' }, { page: 'Settings', icon: '⚙' },
]
const meta: Record<Page, [string, string]> = {
  Dashboard: ['FINANCIAL OVERVIEW', 'A clear view of your money, wherever your business is going.'], Transactions: ['BOOKKEEPING', 'Every local movement, reconciled in one ledger.'], Invoices: ['SALES', 'Create and track professional customer invoices.'], Payments: ['COLLECTIONS', 'Payments recorded against invoices and accounts.'], Income: ['REVENUE', 'Record income and keep revenue reporting current.'], Expenses: ['SPEND CONTROL', 'Keep expenses categorised and visible.'], Customers: ['CONTACTS', 'Understand every customer relationship and balance.'], Suppliers: ['CONTACTS', 'Manage purchase partners and outstanding payables.'], Accounts: ['CASH & BANK', 'Balances across cash, bank, card and wallet accounts.'], 'Tax Center': ['TAX WORKSPACE', 'Configurable calculations for your selected country profile.'], Analytics: ['INTELLIGENCE', 'Local financial data turned into useful patterns.'], Reports: ['REPORT CENTER', 'Generate an up-to-date financial snapshot from local records.'], 'Country Guide': ['COUNTRY PROFILES', 'Configuration-ready business and tax reference profiles.'], Currencies: ['MULTI-CURRENCY', 'Manual exchange-rate management for offline accounting.'], 'Backup & Restore': ['DATA CONTROL', 'Your records remain portable and on this device.'], Settings: ['WORKSPACE', 'Business profile, display preferences and local controls.'], 'About BalancePoint': ['BALANCEPOINT', 'Offline accounting designed for focused small businesses.']
}

export default function App() {
  const [data, setData] = useState<Data>()
  const [page, setPage] = useState<Page>('Dashboard')
  const [dialog, setDialog] = useState<Dialog>(null)
  const [contactMode, setContactMode] = useState<'Customers' | 'Suppliers'>('Customers')
  const [menu, setMenu] = useState(false)
  const [query, setQuery] = useState('')
  const [notice, setNotice] = useState('')
  useEffect(() => { load().then(setData) }, [])
  useEffect(() => { if (!notice) return; const t = window.setTimeout(() => setNotice(''), 2800); return () => clearTimeout(t) }, [notice])
  const commit = async (next: Data, message?: string) => { setData(next); await save(next); if (message) setNotice(message) }
  const search = useMemo(() => !data || query.trim().length < 2 ? [] : [
    ...data.transactions.filter(x => `${x.description} ${x.party} ${x.category}`.toLowerCase().includes(query.toLowerCase())).map(x => ['Transactions', x.description]),
    ...data.invoices.filter(x => `${x.number} ${x.customer}`.toLowerCase().includes(query.toLowerCase())).map(x => ['Invoices', `${x.number} · ${x.customer}`]),
    ...data.customers.filter(x => x.name.toLowerCase().includes(query.toLowerCase())).map(x => ['Customers', x.name]),
  ].slice(0, 6), [data, query])
  if (!data) return <div className="loading"><img src={`${import.meta.env.BASE_URL}brand/balancepoint-logo.png`} alt="BalancePoint"/>Opening your private workspace…</div>
  const add = (kind: Dialog, mode?: 'Customers' | 'Suppliers') => { if (mode) setContactMode(mode); setDialog(kind) }
  const recordTransaction = (transaction: Transaction) => {
    const adjustment = transaction.type === 'Expense' ? -transaction.amount : transaction.amount
    const accounts = data.accounts.map(account => account.name === transaction.account ? { ...account, balance: account.balance + adjustment } : account)
    commit({ ...data, accounts, transactions: [transaction, ...data.transactions] }, 'Transaction recorded successfully.')
    setDialog(null)
  }
  return <div className={`shell ${data.theme}`}>
    <aside className={menu ? 'sidebar open' : 'sidebar'}>
      <div className="brand"><img src={`${import.meta.env.BASE_URL}brand/balancepoint-logo.png`} alt="BalancePoint"/><div><b>Balance<span>Point</span></b><small>OFFLINE ACCOUNTING</small></div><button className="close" onClick={() => setMenu(false)}>×</button></div>
      <nav>{nav.map(item => <button key={item.page} onClick={() => { setPage(item.page); setMenu(false) }} className={page === item.page ? 'active' : ''}><i>{item.icon}</i>{item.page}</button>)}</nav>
      <button className={page === 'About BalancePoint' ? 'about active' : 'about'} onClick={() => setPage('About BalancePoint')}><i>◌</i>About BalancePoint</button>
      <div className="offline"><b><i/> Offline Mode</b><p>All data is stored locally on this device.</p></div>
    </aside>
    {menu && <button className="scrim" onClick={() => setMenu(false)} aria-label="Close navigation"/>}
    <main>
      <header><button className="hamburger" onClick={() => setMenu(true)} aria-label="Open navigation">☰</button><div className="search"><span>⌕</span><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search invoices, contacts, or transactions…"/><div className="search-results">{search.map(([where, label]) => <button key={`${where}-${label}`} onClick={() => { setPage(where as Page); setQuery('') }}><small>{where}</small>{label}</button>)}</div></div><div className="header-actions"><button className="chip">⌄ This month</button><button className="chip currency">₹ INR</button><button className="gear" onClick={() => setPage('Settings')}>⚙</button><button className="avatar">BW</button></div></header>
      <div className="content"><Title page={page} onAdd={() => add(page === 'Invoices' ? 'invoice' : page === 'Customers' || page === 'Suppliers' ? 'contact' : page === 'Accounts' ? 'account' : 'transaction', page === 'Suppliers' ? 'Suppliers' : 'Customers')}/>
        {page === 'Dashboard' && <Dashboard data={data} add={add}/>} {page === 'Transactions' && <Ledger data={data} add={() => add('transaction')}/>} {page === 'Income' && <Ledger data={data} filter="Income" add={() => add('transaction')}/>} {page === 'Expenses' && <Ledger data={data} filter="Expense" add={() => add('transaction')}/>} {page === 'Payments' && <Ledger data={data} filter="Payment" add={() => add('transaction')}/>} {page === 'Invoices' && <Invoices data={data} add={() => add('invoice')}/>} {page === 'Customers' && <Contacts data={data} kind="Customers" add={() => add('contact', 'Customers')}/>} {page === 'Suppliers' && <Contacts data={data} kind="Suppliers" add={() => add('contact', 'Suppliers')}/>} {page === 'Accounts' && <Accounts data={data} add={() => add('account')}/>} {page === 'Tax Center' && <TaxCenter data={data}/>} {page === 'Analytics' && <Analytics data={data}/>} {page === 'Reports' && <Reports data={data} notify={setNotice}/>} {page === 'Country Guide' && <CountryGuide/>} {page === 'Currencies' && <Currencies data={data} commit={commit}/>} {page === 'Backup & Restore' && <Backup data={data} commit={commit} notify={setNotice}/>} {page === 'Settings' && <Settings data={data} commit={commit}/>} {page === 'About BalancePoint' && <About/>}
      </div>
    </main>
    {dialog === 'transaction' && <TransactionForm data={data} close={() => setDialog(null)} done={recordTransaction}/>} {dialog === 'invoice' && <InvoiceForm data={data} close={() => setDialog(null)} done={x => { commit({ ...data, invoices: [x, ...data.invoices] }, `${x.number} created successfully.`); setDialog(null) }}/>} {dialog === 'contact' && <ContactForm kind={contactMode} close={() => setDialog(null)} done={x => { const key = contactMode === 'Customers' ? 'customers' : 'suppliers'; commit({ ...data, [key]: [...data[key], x] }, `${contactMode.slice(0, -1)} saved successfully.`); setDialog(null) }}/>} {dialog === 'account' && <AccountForm close={() => setDialog(null)} done={x => { commit({ ...data, accounts: [...data.accounts, x] }, 'Account added successfully.'); setDialog(null) }}/>} {notice && <div className="toast"><b>✓</b>{notice}</div>}
  </div>
}

function Title({ page, onAdd }: { page: Page; onAdd: () => void }) { const [eyebrow, text] = meta[page]; const action = page === 'Invoices' ? 'Create invoice' : page === 'Customers' ? 'Add customer' : page === 'Suppliers' ? 'Add supplier' : page === 'Accounts' ? 'Add account' : page === 'Dashboard' ? 'Add transaction' : ['Tax Center', 'Analytics', 'Reports', 'Country Guide', 'Currencies', 'Backup & Restore', 'Settings', 'About BalancePoint'].includes(page) ? '' : 'Add record'; return <div className="title"><div><small>{eyebrow}</small><h1>{page}</h1><p>{text}</p></div>{action && <button className="primary" onClick={onAdd}>+ {action}</button>}</div> }
function Dashboard({ data, add }: { data: Data; add: (x: Dialog, mode?: 'Customers' | 'Suppliers') => void }) { const t = totals(data); const values = [['Total income', t.income, '↑ 18.6%', true], ['Total expenses', t.expenses, '↓ 6.2%', false], ['Net profit', t.profit, '↑ 24.8%', true], ['Accounts receivable', t.receivable, '↑ 9.4%', true], ['Accounts payable', t.payable, '↓ 3.1%', false], ['Cash balance', t.cash, '↑ 12.8%', true]] as const; return <><div className="kpis">{values.map(([label, value, trend, plus], index) => <article className="kpi" key={label}><div><span>{label}</span><i>{plus ? '↗' : '↙'}</i></div><b>{money(value, data.currency)}</b><p className={plus ? 'up' : 'down'}>{trend}<small>from last month</small></p><Spark n={index}/></article>)}</div><div className="grid"><section className="panel chart-panel"><PanelTitle title="Income vs expenses" note="Last 6 months"/><Bars data={data}/></section><section className="panel cash"><PanelTitle title="Cash flow" note="This month"/><small>Net cash position</small><b>{money(t.cash, data.currency)}</b><p><strong>↑ 12.8%</strong> compared to last month</p><svg viewBox="0 0 500 135" aria-label="Cash flow trend"><defs><linearGradient id="fill" x1="0" x2="0" y2="1"><stop stopColor="#1fcdf6" stopOpacity=".38"/><stop offset="1" stopColor="#1fcdf6" stopOpacity="0"/></linearGradient></defs><path fill="url(#fill)" d="M0 118 C40 113 52 92 91 103 S137 71 174 87 S223 46 270 68 S320 29 357 55 S409 30 446 40 S480 13 500 20 V135H0Z"/><path fill="none" stroke="#20c9f4" strokeLinecap="round" strokeWidth="4" d="M0 118 C40 113 52 92 91 103 S137 71 174 87 S223 46 270 68 S320 29 357 55 S409 30 446 40 S480 13 500 20"/></svg></section><section className="panel recent"><PanelTitle title="Recent transactions" action="View all"/><div>{data.transactions.slice(-5).reverse().map(x => <TxRow item={x} currency={data.currency} key={x.id}/>)}</div></section><section className="panel spend"><PanelTitle title="Expense distribution" note="By category"/><Donut data={data}/></section><section className="panel quick"><PanelTitle title="Quick actions" note="Keep work moving"/><div className="quick-grid"><Action icon="▤" name="Create invoice" note="Bill a customer" onClick={() => add('invoice')}/><Action icon="↗" name="Add income" note="Record revenue" onClick={() => add('transaction')}/><Action icon="↙" name="Add expense" note="Track spending" onClick={() => add('transaction')}/><Action icon="♙" name="Add customer" note="Grow your book" onClick={() => add('contact', 'Customers')}/></div></section><section className="panel accounts-summary"><PanelTitle title="Account summary" action="Manage accounts"/><div>{data.accounts.map(x => <div className="account-line" key={x.id}><i>{x.type === 'Bank' ? '⌂' : x.type === 'Cash' ? '¤' : '◈'}</i><p><b>{x.name}</b><small>{x.type} · {data.currency}</small></p><b>{money(x.balance, data.currency)}</b></div>)}</div></section></div></> }
function PanelTitle({ title, note, action }: { title: string; note?: string; action?: string }) { return <div className="panel-title"><div><h2>{title}</h2>{note && <p>{note}</p>}</div>{action && <button>{action} →</button>}</div> }
function Spark({ n }: { n: number }) { const lines = ['0,46 16,43 31,51 46,34 62,38 77,22 100,12', '0,25 16,30 31,22 46,29 62,20 77,35 100,29', '0,54 16,47 31,42 46,49 62,30 77,24 100,11']; return <svg className="spark" viewBox="0 0 100 60" preserveAspectRatio="none"><polyline fill="none" stroke="currentColor" strokeWidth="3" points={lines[n % 3]}/></svg> }
function Bars({ data }: { data: Data }) { const labels = ['Dec', 'Jan', 'Feb', 'Mar', 'Apr', 'May']; const chart = labels.map((label, index) => { const month = index === 0 ? 11 : index - 1; const rows = data.transactions.filter(x => new Date(`${x.date}T00:00:00`).getMonth() === month); return { label, income: rows.filter(x => x.type === 'Income').reduce((n,x) => n+x.amount,0), expense: rows.filter(x => x.type === 'Expense').reduce((n,x) => n+x.amount,0) } }); const max = Math.max(...chart.flatMap(x => [x.income,x.expense]), 1); return <><div className="legend"><span><i/> Income</span><span><i/> Expenses</span></div><div className="bars">{chart.map(x => <div key={x.label}><section><i style={{height: `${Math.max(6, x.income/max*100)}%`}}/><i style={{height: `${Math.max(6, x.expense/max*100)}%`}}/></section><small>{x.label}</small></div>)}</div></> }
function Donut({ data }: { data: Data }) { const groups = expensesByCategory(data.transactions).slice(0,4); const all = groups.reduce((n,x) => n+x.value, 0) || 1; const a = groups[0]?.value/all*360 || 0, b = a+(groups[1]?.value/all*360 || 0), c = b+(groups[2]?.value/all*360 || 0); const style = { background: `conic-gradient(#1cccf4 0deg ${a}deg,#5168fd ${a}deg ${b}deg,#8c70f6 ${b}deg ${c}deg,#203762 ${c}deg 360deg)` }; return <div className="donut-wrap"><div className="donut" style={style}><div><small>Total</small><b>{money(all, data.currency)}</b></div></div><div className="donut-legend">{groups.map((x,i) => <p key={x.label}><i className={`c${i}`}/>{x.label}<b>{Math.round(x.value/all*100)}%</b></p>)}</div></div> }
function Action({ icon, name, note, onClick }: { icon: string; name: string; note: string; onClick: () => void }) { return <button onClick={onClick}><i>{icon}</i><b>{name}</b><small>{note}</small></button> }
function TxRow({ item, currency }: { item: Transaction; currency: string }) { const expense = item.type === 'Expense'; return <div className="tx-row"><i className={expense ? 'out' : 'in'}>{expense ? '↙' : '↗'}</i><p><b>{item.description}</b><small>{item.category} · {item.date}</small></p><b className={expense ? 'red' : 'green'}>{expense ? '−' : '+'}{money(item.amount,currency)}</b><span>{item.status}</span></div> }
function Ledger({ data, filter, add }: { data: Data; filter?: TxType; add: () => void }) { const rows = filter ? data.transactions.filter(x => x.type === filter) : data.transactions; return <section className="table-card"><div className="toolbar"><div className="filters"><button className="selected">{filter || 'All'}</button><button>Cleared</button><button>Pending</button></div><button className="outline" onClick={add}>+ Add transaction</button></div><table><thead><tr><th>Date</th><th>Description</th><th>Category</th><th>Account</th><th>Type</th><th className="right">Amount</th><th>Status</th></tr></thead><tbody>{rows.slice().reverse().map(x => <tr key={x.id}><td>{x.date}</td><td><b>{x.description}</b><small>{x.party || 'No contact'}</small></td><td>{x.category}</td><td>{x.account}</td><td><i className={`type ${x.type.toLowerCase()}`}>{x.type}</i></td><td className={`right ${x.type === 'Expense' ? 'red' : 'green'}`}>{x.type === 'Expense' ? '−' : '+'}{money(x.amount,data.currency)}</td><td><span>{x.status}</span></td></tr>)}</tbody></table>{!rows.length && <Empty title="Nothing recorded yet" copy="Add your first transaction to populate this ledger." action="Add transaction" onClick={add}/>}</section> }
function Invoices({ data, add }: { data: Data; add: () => void }) { return <section className="table-card"><div className="toolbar"><div className="filters"><button className="selected">All invoices</button><button>Open</button><button>Paid</button></div><button className="outline" onClick={add}>+ Create invoice</button></div><table><thead><tr><th>Invoice</th><th>Customer</th><th>Issued</th><th>Due</th><th className="right">Total</th><th className="right">Balance</th><th>Status</th></tr></thead><tbody>{data.invoices.map(x => <tr key={x.id}><td><b>{x.number}</b></td><td>{x.customer}</td><td>{x.date}</td><td>{x.dueDate}</td><td className="right">{money(x.amount,data.currency)}</td><td className="right">{money(x.amount-x.paid,data.currency)}</td><td><span className={x.status === 'Paid' ? 'paid' : ''}>{x.status}</span></td></tr>)}</tbody></table></section> }
function Contacts({ data, kind, add }: { data: Data; kind: 'Customers' | 'Suppliers'; add: () => void }) { const contacts = kind === 'Customers' ? data.customers : data.suppliers; return <div className="contact-grid">{contacts.map(x => { const invoices = data.invoices.filter(i => i.customer === x.name); const outstanding = invoices.reduce((n,i) => n+i.amount-i.paid,0); return <article className="contact" key={x.id}><div><i>{x.name.slice(0,2).toUpperCase()}</i><button>•••</button></div><h2>{x.name}</h2><p>{x.company || x.email}</p><section><span><small>{kind === 'Customers' ? 'Total invoiced' : 'Opening balance'}</small><b>{money(kind === 'Customers' ? invoices.reduce((n,i)=>n+i.amount,0) : x.openingBalance,data.currency)}</b></span><span><small>{kind === 'Customers' ? 'Outstanding' : 'Currency'}</small><b>{kind === 'Customers' ? money(outstanding,data.currency) : data.currency}</b></span></section><footer>{x.email || 'No email added'}<button>View profile →</button></footer></article> })}<button className="add-contact" onClick={add}><i>+</i><b>Add {kind.slice(0,-1).toLowerCase()}</b><small>Keep your book complete</small></button></div> }
function Accounts({ data, add }: { data: Data; add: () => void }) { return <><div className="cards">{data.accounts.map(x => <article key={x.id}><div><small>{x.type.toUpperCase()}</small><span>•••</span></div><b>{x.name}</b><strong>{money(x.balance,data.currency)}</strong><footer>{data.currency}<span>LOCAL ACCOUNT</span></footer></article>)}<button onClick={add}>+<span>Add account</span></button></div><section className="panel note"><b>Account balances are local and transparent.</b><p>Assign income and expenses to an account to keep your business cash position clear.</p></section></> }
function TaxCenter({ data }: { data: Data }) { const [amount,setAmount]=useState(10000), [rate,setRate]=useState(18), [inclusive,setInclusive]=useState(false); const result=tax(amount,rate,inclusive); return <div className="tax-grid"><section className="calculator"><div><i>%</i><span><h2>Tax calculator</h2><p>Configured for {data.country} · editable local rates</p></span></div><label>Amount<input type="number" min="0" value={amount} onChange={e=>setAmount(Number(e.target.value))}/></label><label>Tax rate<select value={rate} onChange={e=>setRate(Number(e.target.value))}>{data.taxRates.map(x=><option key={x}>{x}</option>)}</select></label><label className="switch-label">Tax already included<button className={inclusive?'switch on':'switch'} onClick={()=>setInclusive(!inclusive)}><i/></button></label><section className="tax-result"><span>Taxable amount <b>{money(result.net,data.currency)}</b></span><span>Tax amount <b>{money(result.value,data.currency)}</b></span><strong>Final amount <b>{money(result.total,data.currency)}</b></strong></section></section><section className="panel profile"><PanelTitle title="Active tax profile" action="Edit profile"/><b>India <small>GST · configurable components</small></b><div>{data.taxRates.map(x=><span key={x}>{x}%</span>)}</div><p>Tax and regulatory information is provided for general informational and calculation purposes only. Verify current requirements with the relevant government authority or a qualified tax professional.</p></section><section className="panel summary"><PanelTitle title="Tax summary" note="From local transactions"/><div><span>Tax collected<b>{money(data.transactions.filter(x=>x.type==='Income').reduce((n,x)=>n+x.amount*18/100,0),data.currency)}</b></span><span>Tax paid<b>{money(data.transactions.filter(x=>x.type==='Expense').reduce((n,x)=>n+x.amount*18/100,0),data.currency)}</b></span></div></section></div> }
function Analytics({ data }: { data: Data }) { const t=totals(data), groups=expensesByCategory(data.transactions); return <div className="analytics"><section className="panel wide"><PanelTitle title="Revenue & profit trend" note="Actual local transactions"/><div className="metric-row"><span>Revenue<b>{money(t.income,data.currency)}</b></span><span>Net profit<b>{money(t.profit,data.currency)}</b></span><span>Profit margin<b>{t.income ? (t.profit/t.income*100).toFixed(1) : 0}%</b></span></div><Bars data={data}/></section><section className="panel"><PanelTitle title="Top expense categories" note="Share of spend"/><div className="ranking">{groups.map((x,i)=><div key={x.label}><i>{i+1}</i><span><b>{x.label}</b><small>{money(x.value,data.currency)}</small></span><em style={{width:`${x.value/(groups[0]?.value || 1)*100}%`}}/></div>)}</div></section><section className="panel"><PanelTitle title="Receivables aging" note="Invoice balances"/><div className="aging">{[['Current',.58],['1–30 days',.27],['31–60 days',.1],['60+ days',.05]].map(([label, pct])=><div key={label as string}><span><i style={{width:`${Number(pct)*100}%`}}/>{label as string}</span><b>{money(t.receivable*Number(pct),data.currency)}</b></div>)}</div></section></div> }
function Reports({ data, notify }: { data: Data; notify: (x:string)=>void }) { const t=totals(data); const download=(format:'csv'|'json')=>{const body=format==='json'?JSON.stringify({title:'BalancePoint Financial Summary',generatedAt:new Date().toISOString(),totals:t,transactions:data.transactions},null,2):`Metric,Amount\nTotal Income,${t.income}\nTotal Expenses,${t.expenses}\nNet Profit,${t.profit}\nCash Balance,${t.cash}`;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([body],{type:format==='json'?'application/json':'text/csv'}));a.download=`balancepoint-financial-summary.${format}`;a.click();URL.revokeObjectURL(a.href);notify(`Financial summary exported as ${format.toUpperCase()}.`)}; return <div className="reports"><section className="preview"><div><img src={`${import.meta.env.BASE_URL}brand/balancepoint-logo.png`} alt=""/><span><small>{data.business.toUpperCase()}</small><h2>Profit & Loss</h2><p>Current local data · {data.currency}</p></span></div><p>Total revenue <b>{money(t.income,data.currency)}</b></p><p>Operating expenses <b className="red">({money(t.expenses,data.currency)})</b></p><strong>Net profit <b>{money(t.profit,data.currency)}</b></strong><footer>Generated locally by BalancePoint · No financial data was sent anywhere.</footer></section><aside><h2>Export report</h2><p>Built from live local records. Choose a portable format.</p><button onClick={()=>window.print()}>▧ Print / Save PDF</button><button onClick={()=>download('csv')}>▦ Download CSV</button><button onClick={()=>download('json')}>{} Download JSON</button><small><b>Included</b>Business name, currency, generated date and report data.</small></aside></div> }
function CountryGuide() { const countries=[['IN','India','GST','INR','Configurable CGST, SGST, IGST and UTGST components.'],['AE','United Arab Emirates','VAT','AED','VAT and corporate tax guidance framework.'],['SA','Saudi Arabia','VAT','SAR','Business overview, VAT and invoice concepts.'],['OM','Oman','VAT','OMR','Commercial sectors, invoice terms and VAT overview.'],['QA','Qatar','Tax profile','QAR','Configuration-ready country reference.'],['BH','Bahrain','VAT','BHD','Configuration-ready country reference.'],['KW','Kuwait','Tax profile','KWD','Configuration-ready country reference.']]; return <div className="country-grid">{countries.map(([code,name,tax,currency,copy])=><article key={code}><i>{code}</i><span><h2>{name}</h2><p>{copy}</p><b>{tax} <small>{currency}</small></b></span><button>→</button></article>)}<p>Tax and regulatory information is provided for general informational and calculation purposes only. Verify current requirements with the relevant government authority or a qualified tax professional.</p></div> }
function Currencies({ data, commit }: { data: Data; commit: (x:Data,n?:string)=>void }) { const [rates,setRates]=useState(data.rates); return <div className="currencies"><section><i>¤</i><span><small>BASE CURRENCY</small><h2>{data.currency} · ₹</h2><p>Dashboard totals use this local reporting currency.</p></span></section><section className="table-card"><p className="manual">These rates are manual. BalancePoint never fetches exchange rates online.</p><table><thead><tr><th>Currency</th><th>Unit</th><th>Manual rate to {data.currency}</th><th>Updated</th></tr></thead><tbody>{Object.entries(rates).map(([currency,value])=><tr key={currency}><td><b>{currency}</b></td><td>1 {currency}</td><td><input className="rate" type="number" step=".0001" value={value} onChange={e=>setRates({...rates,[currency]:Number(e.target.value)})}/></td><td>On this device</td></tr>)}</tbody></table><button className="primary" onClick={()=>commit({...data,rates},'Manual exchange rates saved locally.')}>Save exchange rates</button></section></div> }
function Backup({ data, commit, notify }: { data:Data; commit:(x:Data,n?:string)=>void; notify:(x:string)=>void }) { const download=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({version:1,backupDate:new Date().toISOString(),data},null,2)],{type:'application/json'}));a.download=`balancepoint-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href);notify('Complete local backup downloaded.')}; const restore=async(e:React.ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file)return;try{const backup=JSON.parse(await file.text());if(!backup.data?.transactions)throw Error();if(!confirm('Replace current local accounting data with this backup?'))return;commit(backup.data,'Backup restored to this device.')}catch{notify('Backup file is invalid or corrupted.')}}; const reset=async()=>{if(!confirm('Clear all BalancePoint data from this device? This cannot be undone.'))return;await erase();location.reload()}; return <div className="backup"><article><i>⤓</i><h2>Back up your data</h2><p>Export every locally stored record into a portable JSON file. Keep it somewhere safe.</p><button className="primary" onClick={download}>Download backup</button><small>Includes {data.transactions.length} transactions, {data.invoices.length} invoices and {data.customers.length+data.suppliers.length} contacts.</small></article><article><i>⤒</i><h2>Restore a backup</h2><p>Import a previous BalancePoint backup. We validate its structure before replacing data.</p><label className="outline file">Choose backup file<input type="file" accept="application/json,.json" onChange={restore}/></label><small>Restoring replaces current local records after confirmation.</small></article><article className="danger"><i>!</i><h2>Reset local data</h2><p>Remove all BalancePoint data stored on this device, including demo records.</p><button onClick={reset}>Clear all data</button><small>This action cannot be undone.</small></article></div> }
function Settings({ data, commit }: { data:Data; commit:(x:Data,n?:string)=>void }) { const [business,setBusiness]=useState(data.business); const [theme,setTheme]=useState(data.theme); return <div className="settings"><section className="panel"><PanelTitle title="Business profile" note="Shown on reports and invoices"/><label>Business name<input value={business} onChange={e=>setBusiness(e.target.value)}/></label><label>Base currency<input value={data.currency} disabled/></label><label>Country profile<input value={data.country} disabled/></label></section><section className="panel"><PanelTitle title="Experience" note="Accessible local preferences"/><label>Theme<select value={theme} onChange={e=>setTheme(e.target.value as 'dark'|'light')}><option value="dark">Dark premium</option><option value="light">Light</option></select></label><p>BalancePoint respects your device’s reduced-motion setting.</p></section><button className="primary save-settings" onClick={()=>commit({...data,business,theme},'Settings saved locally.')}>Save settings</button></div> }
function About() { return <section className="about-card"><img src={`${import.meta.env.BASE_URL}brand/balancepoint-logo.png`} alt="BalancePoint logo"/><small>BALANCEPOINT · OFFLINE ACCOUNTING</small><h2>Your Business Finances.<br/><em>Simplified. Secure. Offline.</em></h2><p>BalancePoint is designed for practical business bookkeeping without a cloud database, required account or internet connection. Financial records remain on this device unless you export them.</p><div><b>Offline-first</b><b>Local database</b><b>Portable backups</b><b>Multi-currency</b></div></section> }
function Empty({ title,copy,action,onClick }: {title:string;copy:string;action:string;onClick:()=>void}) { return <div className="empty"><i>◌</i><b>{title}</b><p>{copy}</p><button className="outline" onClick={onClick}>{action}</button></div> }
function Modal({ title, copy, close, children }: {title:string;copy:string;close:()=>void;children:ReactNode}) { return <div className="modal-bg"><section className="modal"><button className="x" onClick={close}>×</button><small>NEW RECORD</small><h2>{title}</h2><p>{copy}</p>{children}</section></div> }
function TransactionForm({data,close,done}:{data:Data;close:()=>void;done:(x:Transaction)=>void}) { const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);done({id:id(),date:String(f.get('date')),type:String(f.get('type')) as TxType,description:String(f.get('description')),category:String(f.get('category')),account:String(f.get('account')),party:String(f.get('party')),amount:Number(f.get('amount')),status:'Cleared'})};return <Modal title="Add a transaction" copy="This entry updates local dashboard, reports and cash flow." close={close}><form onSubmit={submit}><label>Type<select name="type"><option>Income</option><option>Expense</option><option>Payment</option></select></label><label>Date<input name="date" type="date" required defaultValue={new Date().toISOString().slice(0,10)}/></label><label className="full">Description<input name="description" required placeholder="e.g. Monthly consulting retainer"/></label><label>Amount<input name="amount" min=".01" step=".01" type="number" required/></label><label>Category<input name="category" required placeholder="e.g. Consulting"/></label><label>Account<select name="account">{data.accounts.map(x=><option key={x.id}>{x.name}</option>)}</select></label><label>Customer / supplier<input name="party" placeholder="Optional contact"/></label><button className="primary full">Save transaction</button></form></Modal> }
function InvoiceForm({data,close,done}:{data:Data;close:()=>void;done:(x:Invoice)=>void}) { const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);done({id:id(),number:String(f.get('number')),customer:String(f.get('customer')),date:String(f.get('date')),dueDate:String(f.get('dueDate')),amount:Number(f.get('amount')),paid:0,status:'Draft'})};return <Modal title="Create invoice" copy="Create a local draft. Export or print it from reports." close={close}><form onSubmit={submit}><label>Invoice number<input name="number" defaultValue={`INV-${1001+data.invoices.length}`} required/></label><label>Customer<input name="customer" list="customers" required/><datalist id="customers">{data.customers.map(x=><option key={x.id} value={x.name}/>)}</datalist></label><label>Date<input name="date" type="date" required defaultValue={new Date().toISOString().slice(0,10)}/></label><label>Due date<input name="dueDate" type="date" required/></label><label className="full">Grand total<input name="amount" type="number" min=".01" step=".01" required/></label><button className="primary full">Save invoice draft</button></form></Modal> }
function ContactForm({kind,close,done}:{kind:'Customers'|'Suppliers';close:()=>void;done:(x:Contact)=>void}) { const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);done({id:id(),name:String(f.get('name')),company:String(f.get('company')),email:String(f.get('email')),openingBalance:Number(f.get('balance'))})};return <Modal title={`Add ${kind.slice(0,-1).toLowerCase()}`} copy="Keep complete local contact details for a clearer financial picture." close={close}><form onSubmit={submit}><label className="full">Name<input name="name" required/></label><label>Company<input name="company"/></label><label>Email<input name="email" type="email"/></label><label className="full">Opening balance<input name="balance" type="number" min="0" defaultValue="0"/></label><button className="primary full">Save {kind.slice(0,-1).toLowerCase()}</button></form></Modal> }
function AccountForm({close,done}:{close:()=>void;done:(x:Account)=>void}) { const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);done({id:id(),name:String(f.get('name')),type:String(f.get('type')),balance:Number(f.get('balance'))})};return <Modal title="Add an account" copy="Record where your funds are held for a clearer cash position." close={close}><form onSubmit={submit}><label className="full">Account name<input name="name" required/></label><label>Account type<select name="type"><option>Bank</option><option>Cash</option><option>Credit Card</option><option>Digital Wallet</option></select></label><label>Opening balance<input name="balance" type="number" min="0" defaultValue="0"/></label><button className="primary full">Save account</button></form></Modal> }
